# Конфигурация защиты веток в соответствии с ISO 27001 (A.9.4.1, A.12.1.2, A.14.2.2)

# Защита основной ветки
main:
  protection:
    required_status_checks:
      strict: true
      contexts:
        - ci/github-actions
        - security/code-scanning
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 2
    enforce_admins: true
    required_linear_history: true
    required_signatures: true
    allow_force_pushes: false
    allow_deletions: false

# Защита ветки разработки
develop:
  protection:
    required_status_checks:
      strict: true
      contexts:
        - ci/github-actions
        - security/code-scanning
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 1
    enforce_admins: false
    required_linear_history: true
    required_signatures: true
    allow_force_pushes: false
    allow_deletions: false

# Защита веток релизов
release/*:
  protection:
    required_status_checks:
      strict: true
      contexts:
        - ci/github-actions
        - security/code-scanning
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 2
    enforce_admins: true
    required_linear_history: true
    required_signatures: true
    allow_force_pushes: false
    allow_deletions: false
