# Эти настройки определяют платформы для спонсорства проекта

github: [username] # Замените на ваше имя пользователя GitHub
patreon: # Замените на ваше имя пользователя Patreon
open_collective: # Замените на ваше имя в Open Collective
ko_fi: # Замените на ваше имя пользователя Ko-fi
tidelift: # Замените на имя пакета/платформы и имя пользователя
community_bridge: # Замените на название проекта в Community Bridge
liberapay: # Замените на ваше имя пользователя Liberapay
issuehunt: # Замените на ваше имя пользователя IssueHunt
otechie: # Замените на ваше имя пользователя Otechie
custom: # Замените на до 4 пользовательских URL спонсорства