# These are supported funding model platforms

github: [ludasiksuper555] # GitHub Sponsors
patreon: ai-agency-landing # Patreon page
open_collective: ai-agency-landing # Open Collective
ko_fi: aiagency # Ko-fi page
tidelift: # npm/ai-agency-landing
community_bridge: # AI Agency Landing Page
liberapay: aiagency # Liberapay username
issuehunt: ludasiksuper555 # IssueHunt username
otechie: ludasiksuper555 # Otechie username
custom: ['https://paypal.me/aiagency', 'https://www.buymeacoffee.com/aiagency'] # Custom funding URLs
