blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/your-username/your-repo/discussions
    about: Ask questions and discuss with the community
  - name: 📚 Documentation
    url: https://your-docs-url.com
    about: Check our comprehensive documentation
  - name: 🔒 Security Issues
    url: https://github.com/your-username/your-repo/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 💼 Commercial Support
    url: mailto:support@your-domain.com
    about: Get professional support and consulting
