name: Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    - name: Build
      run: npm run build
      env:
        NEXT_PUBLIC_SITE_URL: https://ludasiksuper555.github.io/AI-Agency-Landing-Page
    - name: Export static files
      run: npm run export || npm run build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        publish_branch: gh-pages
        cname: ludasiksuper555.github.io/AI-Agency-Landing-Page
    - name: Notify deployment status
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: deployments
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: Deployment Status
        SLACK_MESSAGE: 'Deployment to GitHub Pages ${{ job.status }} :rocket:'
        SLACK_FOOTER: 'https://github.com/ludasiksuper555/AI-Agency-Landing-Page'